config/routes.rb
Depot::Application.routes.draw do
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end
  
  devise_for :users
  get 'admin' => 'admin#index'
  
  

  get "sessions/create"
  get "sessions/destroy"
  
  controller :store do
    get '/search' => :index
  end

  
  
  resources :categories
  
  resources :users

  resources :orders

  
  controller :line_items do
    post 'line_items' => 'line_items#create'
    delete 'line_items' => :destroy
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  
  get '*path' => redirect('/')

  root 'store#index', as: 'store'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
    respond_with(@categories)
  end

  def show
    redirect_to categories_path
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category, location: categories_path)
  end

  def update
    @category.update(category_params)
    respond_with(@category, location: categories_path)
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: 'Category Deleted!' }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= link_to '<- Back', categories_path, class: 'btn btn-warning' %>
<div class="container" style="width: 50%; background-color: #444; border-radius: 20px; padding: 20px; margin-top: 20px;">
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "#{type} Product Category", class: 'btn btn-primary', style: 'width: 100%;' %>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<div class="text-center">Edit Category</div>

<%= render 'form', type: 'edit' %>

<!--
<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
-->

app/views/categories/index.html.erb
<div class="container">
  <%= link_to '<i class="glyphicon glyphicon-arrow-left"></i> Back'.html_safe, admin_path, class: 'btn btn-warning'%>
  <div class="pull-right"><%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %></div>
</div>


<div class="text-center" style="font-size: 20px;">Category Listing</div>

<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<div class="container" style="background-color: #444; padding: 20px; margin-top: 20px; border-radius: 20px;">

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Options</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning btn-small'  %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small', style: 'width: 90px;'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @categories, class: 'pagination pull-right'%>

</div>

app/views/categories/new.html.erb
<div class="text-center">New Category</div>

<%= render 'form', type: 'create' %>

<!--<%= link_to 'Back', categories_path %>-->

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>