config/routes.rb
Depot::Application.routes.draw do
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end
  
  devise_for :users
  get 'admin' => 'admin#index'
  
  

  get "sessions/create"
  get "sessions/destroy"
  
  controller :store do
    get '/search' => :index
  end

  
  
  resources :categories
  
  resources :users

  resources :orders

  
  controller :line_items do
    post 'line_items' => 'line_items#create'
    delete 'line_items' => :destroy
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end
  
  get '*path' => redirect('/')

  root 'store#index', as: 'store'
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  belongs_to :category
  
  validates :title, :description, :image_url, :category_id, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'Must be a URL for GIF, JPG, or PNG image.'
  }
  
  def self.latest
    Product.order(:updated_at).last
  end
  
  
  private
  
  def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:create, :update]

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page: 5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  #asdasd
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @category = @product.category_id
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.category_id = @category.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.category_id = @category.id
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end

    def set_category
      if Category.find(params[:product][:category_id])
        @category = Category.find(params[:product][:category_id])
      else
        @category = nil
      end
    end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= link_to '<- Back', products_path, class: 'btn btn-warning'%>
<div class="text-center"><%= type.capitalize %> Product</div>
<div class="container" style="width: 50%; background-color: #444; border-radius: 20px; padding: 20px; margin-top: 20px;">
  <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title , class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description , class: 'form-control'%>
    </div>
    <div class="">
      <%= f.label :category_id %><br />
      <%= f.select :category_id, options_from_collection_for_select(Category.all,'id','name', (@category ? @category : "Select Category" )), class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :image_url %>
      <%= f.text_field :image_url , class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price , class: 'form-control'%>
    </div>
    <div class="actions">
      <%= f.submit "#{type} Product", class: 'btn btn-success', style: "width: 100%;"%>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<%= render 'form', type: 'edit' %>

app/views/products/index.html.erb
<div class="container">
  <%= link_to '<i class="glyphicon glyphicon-arrow-left"></i> Back'.html_safe, admin_path, class: 'btn btn-warning'%>
  <div class="pull-right"><%= link_to 'New Product', new_product_path, class: 'btn btn-primary'%></div> 
</div>


<div class="text-center" style="font-size: 20px;">Product Listing</div>
  

<div class="container" style="background-color: #444; padding: 20px; margin-top: 20px; border-radius: 20px;">

<table class="table">
  <thead>
    <td>Image</td>
    <td>Title</td>
    <td>Description</td>
    <td>Category</td>
    <td>Options</td>
  </thead>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag(product.image_url, class: 'list_image') %></td>
        <td style="width: 100px;"><%= product.title %></td>
        <td style="width: 350px;"><%= truncate(strip_tags(product.description), length: 80) %></td>
        <td style=""><%= product.category.name %></td>
        <td>
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning btn-small' %> 
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-small', style: 'width: 90px;' %>
        </td>
      </tr>
    <% end %>
</table>
  
<%= will_paginate @products, class: 'pagination pull-right' %>
</div>

app/views/products/new.html.erb
<%= render 'form', type: 'create' %>

<!--<%= link_to 'Back', products_path %>-->

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>